Added the ability to add a list of hosts via stdin, and dried up some of the code to accommodate it

diff --git a/mtc b/mtc
--- a/mtc
+++ b/mtc
@@ -22,6 +22,40 @@ mtc_is_running() {
   ipset list mtc >/dev/null 2>&1
 }
 
+add_ip() {
+  if ipset test mtc "$1" >/dev/null 2>&1; then
+    echo "IP address already in list" >&2
+    return 1
+  fi
+
+  if [ ! -n "$2" ]; then
+    echo "Adding IP address $1 to list"
+    ipset add mtc "$1"
+  else
+    echo "Adding IP address $1 to list with a timeout of $2 minute(s)"
+    ipset add mtc "$1" timeout "$(( $2 * 60 ))"
+  fi
+}
+
+add_host() {
+  local ip
+
+  if ! ip="$(dig "$1" a +short +search)"; then
+    echo "Problem running dig" >&2
+    return 1
+  fi
+
+  if [ ! -n "$ip" ]; then
+    echo "Could not find an IP for $1" >&2
+    return 1
+  fi
+
+  # Get only one IP address, and ignore any CNAMEs
+  ip="$(echo "$ip" | tail -n1)"
+
+  add_ip "$ip" "$2"
+}
+
 if [ "$(id -u)" != 0 ]; then
   echo "Must be ran as root" >&2
   exit 1
@@ -84,13 +118,14 @@ case "$1" in
     # Finally create an ipset for holding a list of IP addresses,
     # and the appropriate iptables rules
 
-    # Assumes my script will be the only thing editing the fwmark
+    # Assumes this script will be the only thing editing the fwmark
     # and POSTROUTING chains
 
     ipset new mtc bitmap:ip range "$network/$maskbits" timeout 0
 
     iptables -t mangle -F fwmark
     iptables -t mangle -A fwmark -j CONNMARK --restore-mark
+
     iptables -t mangle -A fwmark -m mark ! --mark 0 -j ACCEPT
     iptables -t mangle -A fwmark -m set --match-set mtc src -j MARK --set-mark "$mark_value"
 
@@ -153,23 +188,23 @@ case "$1" in
       exit 1
     fi
 
-    if ! ip="$(dig +short +search "$2")"; then
-      echo "Problem running dig" >&2
+    add_host "$2" "$3"
+  ;;
+
+  hosts)
+    is_installed dig || { echo "dig not installed" >&2; exit 1; }
+
+    if ! mtc_is_running; then
+      echo "MTC doesn't appear to be running" >&2
       exit 1
     fi
 
-    if [ ! -n "$ip" ]; then
-      echo "Could not find an IP for supplied host" >&2
-      exit 1
-    fi
+    while IFS= read -r host; do
+      add_host "$host" "$2"
+    done
 
-    if [ ! -n "$3" ]; then
-      echo "Adding IP address $ip (resolved from host $2) to list"
-      ipset add mtc "$ip"
-    else
-      echo "Adding IP address $ip (resolved from host $2) to list with timeout of $3 minutes"
-      ipset add mtc "$ip" timeout "$(( $3 * 60 ))"
-    fi
+    # This command should always appear to succeed
+    true
   ;;
 
   list)
@@ -203,13 +238,7 @@ case "$1" in
       exit 1
     fi
 
-    if [ ! -n "$2" ]; then
-      echo "Adding IP address $ip to list"
-      ipset add mtc "$ip"
-    else
-      echo "Adding IP address $ip to list with timeout of $2 minutes"
-      ipset add mtc "$ip" timeout "$(( $2 * 60 ))"
-    fi
+    add_ip "$ip" "$2"
   ;;
 
   help)
@@ -242,12 +271,9 @@ case "$1" in
       exit 1
     fi
 
-    if [ ! -n "$2" ]; then
-      echo "Adding IP address $1 to list"
-      ipset add mtc "$1"
-    else
-      echo "Adding IP address $1 to list with timeout of $2 minutes"
-      ipset add mtc "$1" timeout "$(( $2 * 60 ))"
-    fi
+    add_ip "$1" "$2"
   ;;
 esac
+
+# Don't add anything after the case statement, we want to exit with
+# the exit code of the command ran last in the case statement.
