Tidied up

diff --git a/mtc b/mtc
--- a/mtc
+++ b/mtc
@@ -21,7 +21,11 @@ mtc_is_running() {
   ipset list mtc >/dev/null 2>&1
 }
 
-mkdir "$lock_path" || { echo "Could not acquire lock, exiting without any changes" >&2; exit 1; }
+if ! mkdir "$lock_path"; then
+  echo "Could not acquire lock, exiting without any changes" >&2
+  exit 1
+fi
+
 trap 'rm -r "$lock_path" 2>/dev/null' EXIT
 
 if [ "$(id -u)" != 0 ]; then
