Added host lookup functionality

diff --git a/mtc b/mtc
--- a/mtc
+++ b/mtc
@@ -7,10 +7,8 @@ check_if_installed() {
   fi
 }
 
-check_if_installed tc
-check_if_installed ipset
-
 mark_value=6
+network=192.168.1.0/24
 
 case "$1" in
   init)
@@ -52,7 +50,7 @@ case "$1" in
     done
 
     # Finally create an ipset for holding a list of IP addresses and the appropriate iptables rules
-    ipset new mtc bitmap:ip range 192.168.1.0/24
+    ipset new mtc bitmap:ip range "$network"
 
     iptables -t mangle -F fwmark
     iptables -t mangle -A fwmark -j CONNMARK --restore-mark
@@ -83,6 +81,28 @@ case "$1" in
     echo "Connections marked: $(grep -c mark="$mark_value" /proc/net/nf_conntrack)"
   ;;
 
+  host)
+    check_if_installed dig
+
+    if [ ! -n "$2" ]; then
+      echo "No host argument supplied." >&2
+      exit 1
+    fi
+
+    ip="$(dig +short +search "$2")"
+
+    if [ ! -n "$ip" ]; then
+      echo "Could not find an IP for supplied host." >&2
+      exit 1
+    fi
+
+    ipset add mtc "$ip"
+  ;;
+
+  list)
+    ipset list mtc
+  ;;
+
   help)
     echo "Usage: mtc COMMAND|IPV4-ADDRESS"
     echo
@@ -93,6 +113,7 @@ case "$1" in
     echo "  clear|flush - wipe the IPv4 addresses being throttled."
     echo "  halt|kill   - deinitialise setup, removing all qdiscs and iptables rules."
     echo "  count       - display a count of marked connections."
+    echo "  host HOST   - add an IP address to be throttled by hostname."
     echo "  help        - display this help snippet."
   ;;
 
